# Generated by Django 2.1.4 on 2019-03-15 00:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donghu', '0002_auto_20190314_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='name_zh',
            field=models.CharField(max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
