# Generated by Django 2.1.4 on 2019-04-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donghu', '0003_module_name_zh'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sustime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recommentary',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
