# Generated by Django 2.1.4 on 2019-04-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donghu', '0006_auto_20190407_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='question',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
