# Generated by Django 2.1.4 on 2019-04-07 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donghu', '0007_auto_20190407_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donghu.Question'),
            preserve_default=False,
        ),
    ]
