"""
Django settings for donghubbs project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_DIRS = os.path.join(BASE_DIR, 'static')

# 配置上传文件存放的路径
MEDIA_URL = '/media/'

# 指定的文件存放的根目录，是一个字符串路径
MEDIA_ROOT = os.path.join(BASE_DIR,'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'y5i3bzikb#+gfyzedne9l*4#gsy*k+1l^9cmy^8k5cklor)*52'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.43.66','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'donghu.apps.DonghuConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.sites',
    # Abobe list was created by django.
]
SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'donghubbs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'donghubbs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'donghubbs',
        # 'USER': 'donghu',
        # 'PASSWORD': 'AdongHu.19',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# 默认值为django.contrib.auth.backends.ModelBackend，当用户is_active=False时验证系统返回None
# 改为此项，则不做此限制
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.AllowAllUsersModelBackend']

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Login
LOGIN_URL = '/login/'



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/
STATICFILES_DIRS = [STATIC_DIRS, MEDIA_ROOT]
STATIC_URL = '/static/'


# set Browser-Length 
# It is disabled by default
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
# Only used when above variable is False
# It is enabled by default
SESSION_COOKIE_AGE = 24 * 60 * 60

# Email
# Email设置
# 管理员邮箱
ADMINS = (
    ('3243148844@qq.com',),
)
# 非空链接，却发生404错误，发送通知MANAGERS
SEND_BROKEN_LINK_EMAILS = True
MANAGERS = ADMINS
 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # 固定写法
EMAIL_HOST = 'smtp.qq.com'                                # QQ邮箱SMTP服务器(邮箱需要开通SMTP服务)
EMAIL_PORT = 25                                           # QQ邮箱SMTP服务端口
EMAIL_HOST_USER = '3243148844@qq.com'                           # 我的邮箱帐号
EMAIL_HOST_PASSWORD = 'ktbpqtbvhrjpdahc'                  # 授权码 - 密码  xamniqaasycsdjag / medxhyzcxodcdjhc
EMAIL_SUBJECT_PREFIX = 'django website'                   # 为邮件标题的前缀,默认是'[django]'
EMAIL_USE_TLS = False                                      # 开启安全链接
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER                      # 不设置会出错
# DEFAULT_FROM_EMAIL = SERVER_EMAIL = EMAIL_HOST_USER     # 设置发件人
EMAIL_FROM = '3243148844@qq.com'                                # 你的 QQ 账号
